In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df.head()

,subject,year,topic,exam,exercise_number,statement,exercise_type
0,Física,2016,Física cuántica y nuclear,Junio,"Ejercicio 2, Opción B",a) Teoría de Einstein del efecto fotoeléctrico...,no clasificado
1,Física,2016,Física cuántica y nuclear,Junio,"Ejercicio 4, Opción A",El * Pb emite dos partículas beta y se transfo...,no clasificado
2,Física,2016,Física cuántica y nuclear,Reserva 2,"Ejercicio 4, Opción A",a) Calcule la energía liberada en el proceso p...,no clasificado
3,Física,2016,Física cuántica y nuclear,Reserva 3,"Ejercicio 2, Opción A",a) ¿Qué se entiende por dualidad onda-corpúscu...,no clasificado
4,Física,2016,Física cuántica y nuclear,Reserva 4,"Ejercicio 2, Opción A",a) Escriba la ley de desintegración radiactiva...,no clasificado

In [6]:
def form_exercise_string(row):
    exam = [row['exam'].upper() ]
    exercise = [i.upper() for i in row['exercise_number'].split(', ')]
    return '. '.join(exam + exercise)

In [8]:
df['exercise'] = df.apply(form_exercise_string, axis = 1)

In [11]:
df.sample(10)

,subject,year,topic,exam,exercise,exercise_type,statement
406,Mates CCSS,2009,Contraste De Hipótesis,Ponencia,PONENCIA. EJERCICIO 3,no clasificado,Sólo el 75% de los alumnos de un centro de ens...
2501,Química,2021,Configuración Electrónica,Reserva 3,RESERVA 3. EJERCICIO B1,Combinaciones de números cuánticos,Un átomo X tiene 34 protones y 44 neutrones. O...
3195,Química,2001,Formulación,Junio,JUNIO. EJERCICIO 1. OPCIÓN B,no clasificado,Formule o nombre los siguientes compuestos: a)...
837,Mates CCSS,2009,Inferencia Estadística,Reserva 2,RESERVA 2. EJERCICIO 3. PARTE II. OPCIÓN A,no clasificado,"Escriba todas las muestras de tamaño 2 que, me..."
3070,Química,2007,Termoquímica,Septiembre,SEPTIEMBRE. EJERCICIO 6. OPCIÓN B,no clasificado,"respectivamente, —228,—394 y —286 kJ/mol, calc..."
2845,Química,2012,Reactividad Orgánica,Reserva 4,RESERVA 4. EJERCICIO 4. OPCIÓN A,Isomería geométrica,Escriba la fórmula desarrollada de:\na) Dos co...
1265,Mates CCSS,2005,Programación Lineal,Septiembre,SEPTIEMBRE. EJERCICIO 1. OPCIÓN B,no clasificado,Sea el siguiente sistema de inecuaciones: x + ...
1975,Química,2007,Cantidad Química,Junio,JUNIO. EJERCICIO 4. OPCIÓN A,no clasificado,"Un recipiente cerrado contiene oxígeno, despué..."
2371,Química,2008,Configuración Electrónica,Reserva 2,RESERVA 2. EJERCICIO 2. OPCIÓN A,Verdadero o Falso,Razone si son verdaderas o falsas las siguient...
2671,Química,2017,Reacciones Redox,Junio,JUNIO. EJERCICIO 6. OPCIÓN B,no clasificado,"Dada la reacción: K ,Cr,O, + FeSO, + H,SO, > F..."

In [10]:
# subject,year,topic,exam,exercise_number,statement,exercise_type
df = df[['subject', 'year', 'topic', 'exam', 'exercise', 'exercise_type', 'statement']]

In [12]:
df.to_csv('data.csv', index = False)