In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("../classifications/final_classification_chemistry.csv")

In [5]:
df.sample(10)

,year,subject,topic,exam,exercise,exercise_type
1097,2005,química,formulacion,Junio,Ejercicio 1 Opción A,inorgánica y orgánica
1392,2025,NaN,redox,Reserva 2,Ejercicio 3A,ley de Faraday
22,2022,química,acido_base,Junio,Ejercicio C3,neutralización ácido base
1328,2011,química,reactividad_organica,Reserva 3,Ejercicio 4 Opción B,isomería
1333,2010,química,reactividad_organica,Reserva 3,Ejercicio 4 Opción A,isomería
591,2018,NaN,conf_electronica,Junio,Ejercicio 2 Opción B,verdadero o falso
565,2021,NaN,conf_electronica,Reserva 2,Ejercicio B1,indicar qué configuraciones electrónicas son c...
1577,2003,NaN,redox,Reserva 2,Ejercicio 3 Opcion A,pilas galvánicas
962,2008,química,equilibrio_quimico,Reserva 4,Ejercicio 3 Opcion A,principio de LeChatelier
574,2020,NaN,conf_electronica,Reserva 2,Ejercicio B1,especies isoelectrónicas (Na+ y Ne)

In [8]:
df.subject.unique()

<StringArray>
['quimica']
Length: 1, dtype: str

In [7]:
df.subject = "quimica"

In [9]:
df.isna().sum()

year              0
subject           0
topic             1
exam              2
exercise          2
exercise_type    20
dtype: int64

In [17]:
df[df.topic.isna()]

Empty DataFrame
Columns: [year, subject, topic, exam, exercise, exercise_type]
Index: []

In [16]:
df = df.drop(df.index[1957])

In [19]:
df[df.exercise_type.isna()]

,year,subject,topic,exam,exercise,exercise_type
244,2013,quimica,cantidad_qui,NaN,NaN,NaN
514,2012,quimica,cinetica,Septiembre,Ejercicio 3 Opción B,NaN
523,2003,quimica,cinetica,Reserva 3,Ejercicio 3 Opción B,NaN
525,2001,quimica,cinetica,Junio,Ejercicio 3 Opción B,NaN
526,2001,quimica,cinetica,Reserva 3,Ejercicio 3 Opción B,NaN
527,2000,quimica,cinetica,Reserva 1,Ejercicio 4 Opción B,NaN
998,2003,quimica,equilibrio_quimico,Reserva 1,Ejercicio 3 Opcion A,NaN
1398,2024,quimica,redox,Reserva 3,Ejercicio B5,NaN
1500,2013,quimica,redox,Septiembre,Ejercicio 3 Opción A,NaN
1503,2012,quimica,redox,Reserva 1,Ejercicio 3 Opción A,NaN
1525,2010,quimica,redox,Septiembre,Ejercicio 3 Opción B,NaN
1536,2008,quimica,redox,Reserva 1,Ejercicio 3 Opción A,NaN
1538,2008,quimica,redox,Reserva 2,Ejercicio 3 Opción B,NaN
1544,2007,quimica,redox,Reserva 2,Ejercicio 3 Opción A,NaN
1569,2004,quimica,redox,Reserva 2,Ejercicio 3 Opción B,NaN
1582,2002,quimica,redox,Junio,Ejercicio 3 Opción B,NaN
1588,2002,quimica,redox,Septiembre,Ejercicio 3 Opcion A,NaN
1593,2001,quimica,redox,Reserva 3,Ejercicio 3 Opción A,NaN
1603,2000,quimica,redox,Reserva 4,Ejercicio 3 Opcion A,NaN

In [23]:
df[df.exam.isna()]

Empty DataFrame
Columns: [year, subject, topic, exam, exercise, exercise_type]
Index: []

In [22]:
df = df.drop(df.index[244])

In [24]:
df.topic.unique()

<StringArray>
[          'acido_base',     'cantidad_quimica',             'cinetica',
     'conf_electronica',       'enlace_quimico',   'equilibrio_quimico',
          'formulacion', 'reactividad_organica',                'redox',
          'solubilidad',         'termoquimica']
Length: 11, dtype: str

In [25]:
df.to_csv("../classifications/clean_chemistry.csv", index = False)

In [26]:
df.sample(10)

,year,subject,topic,exam,exercise,exercise_type
1620,2022,quimica,solubilidad,Junio,C2,cálculo de la solubilidad (efecto ion común)
804,2008,quimica,enlace_quimico,Septiembre,Ejercicio 2 Opción B,verdadero o falso
914,2015,quimica,equilibrio_quimico,Reserva 1,Ejercicio 6 Opción A,grado de disociación (dato)
655,2008,quimica,conf_electronica,Junio,Ejercicio 2 Opción A,isoelectrónicos
166,2007,quimica,acido_base,Reserva 2,Ejercicio 4 Opción A,hidrólisis de sales
1458,2018,quimica,redox,Septiembre,Ejercicio 6 Opción A,ley de Faraday
1757,2014,quimica,termoquimica,Reserva 3,Ejercicio 3 Opción B,estudio de espontaneidad
468,2001,quimica,cantidad_quimica,Reserva 3,Ejercicio 4 Opcióon A,disoluciones
753,2018,quimica,enlace_quimico,Septiembre,Ejercicio 3 Opción A,propiedades del tipo de enlace
1607,2025,quimica,solubilidad,Julio,Ejercicio 2B,efecto del ion común teórico